export const systems = {
  fullBody: {
    label: "ZERO",
    title: "The Body",
    description: [
      "ZERO is the Existence Layer of The Network.",
      "The question 'Am I?' implies existence. Just as the Body embodies existence for the Soul, ZERO embodies existence for The Collective.",
      "The Human Body represents the ultimate hierarchical structure for a single organism. Similarly, ZERO represents the ultimate hierarchical structure for multiple organisms, i.e., society.",
      "As the Human Body is the ideal network of atoms, ZERO is the ideal network of bits.",
    ],
    glbPath: "/models/HumanAnatomyTest3.glb",
    systems: {
      muscular: {
        label: "ZChain",
        title: "Muscular System",
        description: [
          "ZChain is The Destiny Layer of The Network.",
          "The question 'To where am I going?' implies destiny. Just as the Muscular System embodies destiny for the body, ZChain embodies destiny for the network.",
          "Muscles guide the body's movement toward its intended goals, directly influencing physical destiny. Likewise, ZChain guides the network's progression toward achieving its long-term objectives, directly influencing digital destiny.",
          "Just as muscles adapt and grow stronger under stress, ZChain adapts and expands its capacity to handle increased network demand.",
          "Just as muscle memory stores learned movements, ZChain stores all transactions, messages, and transfers, ensuring reliable continuity.",
        ],
        groupPath: "Complete_human_anatomy/Muscular_Subgroup",
        parts: {},
      },
      digestive: {
        label: "ZODES",
        title: "Digestive System",
        description: [
          "ZODES are the Integration Layer of The Network.",
          "The question 'Am I enough?' implies integration. Just as the Digestive System embodies integration for the body, ZODES embody integration for the network.",
          "The Digestive System transforms external nutrients into usable energy, effectively integrating environmental resources into the body for growth. Similarly, ZODES can be set up by anyone, integrating the computational power necessary for network growth.",
          "Just as digestion processes and distributes essential nutrients throughout the body, ZODES securely process, store, and replicate data across the network, maintaining optimal functionality and balance.",
        ],
        groupPath: "Complete_human_anatomy/Digestive_Subgroup",
        parts: {},
      },
      respiratory: {
        label: "ZBI",
        title: "Respiratory System",
        description: [
          "ZBI is the Condition Layer of The Network.",
          "The question 'How am I?' implies condition. Just as the Respiratory System embodies condition management for the body, ZBI embodies condition management for the network.",
          "The Respiratory System sustains the body's vitality by continuously supplying oxygen. Likewise, ZBI maintains the network's vitality by continuously supplying essential tokens.",
          "Effective respiratory function maintains optimal bodily conditions; similarly, efficient token distribution by ZBI maintains optimal network conditions.",
        ],
        groupPath: "Complete_human_anatomy/Respiratory_Subgroup",
        parts: {},
      },
      lymphatic: {
        label: "ZID",
        title: "Lymphatic System",
        description: [
          "ZID is the Identity Layer of The Network.",
          "The question 'Who am I?' implies identity. Just as the Lymphatic System embodies identity protection for the body, ZID embodies identity protection for the network.",
          "The Lymphatic System identifies and eliminates harmful foreign entities, safeguarding bodily integrity. Similarly, ZID authenticates users and defends against unauthorized access, safeguarding network integrity.",
          "ZID ensures secure interactions within the network, acting as a vigilant gatekeeper analogous to the body's lymphatic defense system.",
        ],
        groupPath: "Complete_human_anatomy/Lymphatic_Subgroup",
        parts: {},
      },
      nervous: {
        label: "ZDAO",
        title: "Nervous System",
        description: [
          "ZDAO is the Agency Layer of The Network.",
          "The question 'Do I have choice?' implies agency. Just as the Nervous System embodies agency for the body, ZDAO embodies agency for the network.",
          "The Nervous System interprets and responds to stimuli, coordinating action throughout the body. ZDAO likewise interprets and responds to collective input, coordinating decentralized governance.",
          "Just as the nervous system routes all bodily signals to the brain, every consent-based community in the network transmits its intent through token voting — ensuring responsive, sovereign decision-making.",
          "ZDAO Structure Overview:",
          "- **INITIATION** (Right Brain): Proposes new directives (Masculine Principle)",
          "- **INTEGRATION** (Left Brain): Implements approved directives (Feminine Principle)",
          "- **SIGNAL** (Spinal Cord & Nerves): Represents community agency and voting input",
          /*"🧠 12 Cranial Branches (Advisory Ministries):",
          "Each branch reflects a cranial nerve, serving as a symbolic and functional department:",
          "- **I. Olfactory (Scent)** → Department of Culture & Spirit – Senses the cultural climate and emotional resonance of the network.",
          "- **II. Optic (Vision)** → Department of Defense – Constantly surveys for existential threats and monitors perimeter integrity.",
          "- **III. Oculomotor (Eye Movement)** → Department of Navigation – Guides strategic mobility and directional clarity.",
          "- **IV. Trochlear (Eye Rotation)** → Department of Innovation – Adjusts network perspectives; manages disruptive insight.",
          "- **V. Trigeminal (Sensation & Chewing)** → Department of Infrastructure – Handles foundational structure and input/output channels.",
          "- **VI. Abducens (Lateral Eye Movement)** → Department of Expansion – Coordinates external engagement and cross-network relations.",
          "- **VII. Facial (Expression)** → Department of Communication – Governs expressive systems, messaging protocols, and transparency.",
          "- **VIII. Vestibulocochlear (Hearing & Balance)** → Department of Consensus – Maintains equilibrium across decisions and community voices.",
          "- **IX. Glossopharyngeal (Taste & Swallowing)** → Department of Resource Allocation – Manages intake, distribution, and internal flow of value.",
          "- **X. Vagus (Autonomic Control)** → Department of Internal Affairs – Regulates background processes, homeostasis, and resilience.",
          "- **XI. Accessory (Neck Movement)** → Department of Logistics & Coordination – Facilitates large-scale network alignment.",
          "- **XII. Hypoglossal (Tongue Control)** → Department of Protocols & Language – Manages governance language, smart contract standards, and semantic clarity.",*/
        ],
        groupPath: "Complete_human_anatomy/Nervous_Subgroup",
        parts: {
          ZRight: {
            label: "Council of Initiation (INITIATION)",
            title: "Right Hemisphere",
            description: [
              "INITIATION is one of three branches of ZDAO. Just as the Right Brain governs reactive, intuitive agency for the body, INITIATION governs the directional impulse of the network.",
              "This council proposes new directives for the network based on pattern recognition, rapid judgment, and strategic foresight — embodying the Hermetic masculine principle of initiation and projection.",
              "Any new proposal must be passed by community vote (via token-weighted consensus) before proceeding to implementation.",
              "To prevent consolidation of power, community tokens can trigger a recall vote. If a predetermined percentage of tokens signal for new council members, a full network-wide election is triggered.",
              "Biological Parallel: The right hemisphere often initiates action through creative impulse or instinctual decision — but it only acts in coordination with sensory feedback from the body. Likewise, INITIATION cannot act without SIGNAL’s vote-driven feedback.",
            ],
            nodeName:
              "Complete_human_anatomy/Nervous_Subgroup/Brain_Subgroup/ZRight_Part",
          },
          ZLeft: {
            label: "Council of Integration (INTEGRATION)",
            title: "Left Hemisphere",
            description: [
              "INTEGRATION is one of three branches of ZDAO. Just as the Left Brain governs structure, reasoning, and interpretation for the body, INTEGRATION governs long-term implementation and systemic integrity for the network.",
              "After INITIATION proposals pass, INTEGRATION translates those directives into functioning infrastructure, processes, or protocols during a grace period.",
              "During this grace period, any community may initiate a vote to cancel the directive before it is finalized. If no cancellation passes, the directive becomes permanent.",
              "This council embodies the Hermetic feminine principle of form-building, nurturing complex systems through logic and synthesis.",
              "Biological Parallel: The left hemisphere integrates motor plans, language, and abstract reasoning — translating vision into coordinated structure. INTEGRATION likewise ensures every change is translated into coherent, accountable structure.",
            ],
            nodeName:
              "Complete_human_anatomy/Nervous_Subgroup/Brain_Subgroup/ZLeft_Part",
          },
          ZCenter: {
            label: "SIGNAL",
            title: "Spinal Cord & Nerves",
            description: [
              "SIGNAL is one of three branches of ZDAO. Just as the spinal cord transmits nerve impulses and governs reflexes, SIGNAL represents the foundational consent-driven communication of the network.",
              "SIGNAL is composed of DAOs — consentual communities — each fully sovereign but interconnected through token-based coordination.",
              "Each community governs how its votes are allocated — reflecting sovereignty and decentralization at every layer.",
              "SIGNAL holds both initiating and restraining power — enabling votes to approve proposals from INITIATION or cancel implementations from INTEGRATION during grace periods.",
                "In addition, if a predetermined percentage of total network tokens support replacing council members, SIGNAL triggers a full-network recall vote.",
              "Biological Parallel: The spinal cord reflexively regulates local functions while transmitting crucial signals to the brain. SIGNAL mirrors this role by autonomously managing local decisions and channeling upward consensus to shape ZDAO’s direction.",
            ],
            nodeName: "Complete_human_anatomy/Nervous_Subgroup/ZCenter_Part",
          },
        },
      },
      cardiovascular: {
        label: "ZXP",
        title: "Cardiovascular System",
        description: [
          "ZXP is the Purpose Layer of The Network.",
          "The question 'Why am I?' implies purpose. Just as the Cardiovascular System embodies purpose for the body, ZXP embodies purpose for the network.",
          "The Cardiovascular System circulates blood efficiently, delivering nutrients precisely where needed to sustain life. Similarly, ZXP circulates tokens efficiently, delivering resources precisely where needed to sustain network functionality.",
          "Just as circulation maintains bodily health by efficient resource delivery, ZXP maintains network health through strategic token distribution.",
        ],
        groupPath: "Complete_human_anatomy/Cardiovascular_Subgroup",
        parts: {
          ZCon: {
            label: "ZConstitution",
            title: "Heart",
            description: [
              "ZConstitution are the principles the network lives by:",
              "Sovereignty -> Individual and collective ownership of digital property.",
              "Decentralization -> Collective decision-making, network operation and processing with no central point of failure.",
              "Privacy -> Strong personal data privacy with end-to-end encryption.",
              "Censorship-Resistance -> No possibility for third-party censorship or intervention between users and their data.",
              "Open Source -> All code is freely accessible, can be reused and commercialized without permission under the MIT license",
              "Just as the heart is the principles we live by so is ZConstituion the principles by which the network lives by.",
              "Just as the heart coordinates the Cardiovascular System so does ZConstitution coordinate ZXP",
              "Just as our hearts represent our inner nature so does ZConstitution represent the networks inner nature.",
            ],
            nodeName:
              "Complete_human_anatomy/Cardiovascular_Subgroup/ZCon_Part",
          },
        },
      },
      reproductive: {
        label: "ZSpace",
        title: "Reproductive System",
        description: [
          "ZSpace is the Continuity Layer of The Network.",
          "The question 'When am I?' implies continuity. Just as the Reproductive System embodies continuity through generational creation, ZSpace embodies continuity through ongoing digital creation.",
          "The Reproductive System ensures the perpetuation of life by creating offspring. Likewise, ZSpace ensures perpetual growth by continuously generating new network experiences and innovations.",
          "Through continual creation, both systems guarantee the ongoing existence and evolution of their respective domains.",
        ],
        groupPath: "Complete_human_anatomy/Reproductive_Subgroup",
        parts: {},
      },
      skeletal: {
        label: "ZOS",
        title: "Skeletal System",
        description: [
          "ZOS is the Essence Layer of The Network.",
          "The question 'What am I?' implies essence. Just as the Skeletal System embodies foundational essence for the body, ZOS embodies foundational essence for the network.",
          "The Skeletal System provides structural integrity, supporting and enabling bodily function. Similarly, ZOS provides the structural integrity necessary for supporting and enabling network operations.",
          "Just as bones form the framework upon which the body depends, ZOS forms the foundational framework upon which the network operates.",
        ],
        groupPath: "Complete_human_anatomy/Skeletal_Subgroup",
        parts: {},
      },
      integumentary: {
        label: "ZNS",
        title: "Integumentary System",
        description: [
          "ZNS is the Context Layer of The Network.",
          "The question 'Where am I?' implies context. Just as the Integumentary System embodies contextual boundaries for the body, ZNS embodies contextual boundaries for the network.",
          "The Integumentary System interfaces between the body and external environment, regulating interactions and boundaries. Similarly, ZNS interfaces between the network and external digital environment, managing identity and regulating interactions.",
          "Just as skin protects and contextualizes bodily presence, ZNS protects and contextualizes network presence.",
        ],
        groupPath: "Complete_human_anatomy/Integumentary_Subgroup",
        parts: {},
      },
    },
  },
};
